### ISSUE TITLE
need to get args on Group

### ISSUE THREAD

**Issue by ghost** [Didericis/permissions-mixin#1]
Hi Didericis,
I would like to set the group as a function of one element inside the object to be validated (an Id that refers to another collection/document).

Two questions:
1) is it possible? If not, should I use the allow function (but in this case it seems to me I loose completely the benefit of this package)

2) is the mixin happening before or after the validation?
if it comes before I've to "check/validate"the object.referenceId that I want to use?

**Comment by Didericis** [comment]
Hey, thanks for using my mixin!

If I understand your first question correctly, I think you can accomplish what you want by creating an additional permission object. For example, let's say you have an object id as an input and two groups, `red` and  `blue`. If you want to only allow group `red` when the object exists, and only allow group `blue` when the object doesn't exist, you can do this:

``` js
const fooBar = new ValidatedMethod({
    name: 'fooBar',
    mixins: [PermissionsMixin],
    allow: [{
        roles: ['role1', 'role2'],
        group: 'red',
        allow({myId}) {
            return (collection1.findOne(myId) !== undefined);
        }
    }, {
        roles: ['role1', 'role2'],
        group: 'blue',
        allow({ input }) {
            return (collection2.findOne(myId) !== undefined);
        }
    }],
    validate: new SimpleSchema({
        input: { type: String }
    }).validator(),
    run({input}) {
        // do something
    }
});
```

If you think what you want to do cannot be accomplished in this fashion, let me know what the problem is in more detail so I can better understand what's going/help out/better understand what limitations this mixin might have.

As for your second question, the mixin happens after the validation. However, for both this mixin and the core validated-method package, validation is only done when `call` is used, not `run` or `runTrusted`.
