### ISSUE TITLE
/allow: true/ could allow only logged-in users

### ISSUE THREAD

**Issue by omasopust** [Didericis/permissions-mixin#3]
Hi Didericis,
first of all, thank you for this excelent package. I have an idea for a little tweak, though. Your package lacks functionality for one particular use case and that is when you want to allow **all logged in** users.

Yes, you could use `tunifight:loggedin-mixin`, but I like to have as few packages as possible. On the other hand, the current behaviour of allowing all users (logged in or not) can be, if I'm right, easily done by not including the mixin at all. IMO this could be a nice addition to your package and a convinient way to solve this use case. Plus the implementation should be quite quick from what I looked in the code.

Whan do you think, is it good or bad idea? Or does it go against some internal logic of the package? To be honest, I actually expected this behaviour and was quite suprised, when I could run methods with `allow: true` while being logged out.

Thanks and keep up the good work!

**Comment by Didericis** [comment]
Hey, thanks for the positive feedback!

I think it's definitely a good idea to do a simple log on check in this package, but I'd prefer to keep the current behavior for `allow: true`. The main reason is that I prefer to extend the `ValidatedMethod` class into a `SecuredMethod` class so that my methods automatically have this mixin. That way I can use that class for all my new method definitions and deny everyone by default instead of allowing everyone. But then if I want to open a method up to everyone, there then needs to be a way to do that explicitly, and `allow: true` felt pretty intuitive. I updated the documentation and added a bit on this towards the end if you want to take a look at it.

I did, however, make a similar means of checking for a logged in user and pushed in up. If you want to do a check for all logged in users, you can now do `allow: PermissionsMixin.LoggedIn`. This is the same as `allow: [{ roles: true, group: true }]`, which is a part of some more options I allowed for roles and group (each can be either true, a string, or an array of strings now).

**Comment by omasopust** [comment]
Wow, this is great news! I think that your solution is even better. Thanks for the fast response and implementation, I'm going to try it :)
