### ISSUE TITLE
New Feature: Group parameter accepts a function

### ISSUE THREAD

**Issue by todda00** [Didericis/permissions-mixin#6]
It would be nice to be able to set the group name using variables from the method parameters. If the group property could be a function which received the method parameters and could return the group name for use in validation.

I can create a PR with this functionality.

**Comment by Didericis** [comment]
Hey @todda00 , thanks for the feedback! Sorry it's taken me forever to respond. I've been really busy lately and this kept getting pushed under my radar.

I'm a bit hesitant to incorporate this because I'm not sure if I see the use for it and think the `allow` function could be used for most of what you want. Part of the reason for having a `roles` and `groups` parameter instead of just an array of `allow` functions was to make it easier to tell which roles and groups were allowed to use certain methods by quickly looking at them. The idea was to be able to look at a method and say "Does `roleA` in `groupB` have access to this method?" and find a role doc in the array with `roleA` and `groupB` in it. The `allow` function is what is supposed to conditionally allow users based on the parameters passed into the method.

If i understand the problem you're trying to solve correctly, it seems like you want the methods to have different behaviors based on the parameters passed to them. If `methodA` has one set of parameters, you would like it to allow users from `groupA`, and if it has another set of parameters, you would like it to allow users from `groupB`. Instead of changing the security groups through which the permissions mixin verifies if the user is correct dynamically based on a method parameter, I think it would be safer and possible more clear to do something like this;

``` js
const methodA = new ValidatedMethod({
  mixins: [PermissionsMixin],
  name: 'methodA',
  allow: [{ roles: true, group: ['groupA'], }],
  validate: null,
  run() {
    // Do something A like
  }
});

const methodB = new ValidatedMethod({
  mixins: [PermissionsMixin],
  name: 'methodB',
  allow: [{ roles: true, group: ['groupB'], }],
  validate: null,
  run() {
    // Do something B like
  }
});

const methodGeneric = new ValidatedMethod({
  mixins: [PermissionsMixin],
  name: 'methodGeneric',
  allow: [{ roles: true, group: ['groupA', 'groupB'], }],
  validate: null,
  run({param}) {
    if (param) methodA.run.call(this);
    methodB.run.call(this);
  }
});
```

If you think I'm missing something or have a specific problem that you think this approach doesn't address/find something lacking, please let me know.

**Comment by todda00** [comment]
No need to apologize, work takes us in many directions, and I totally understand open source projects can fall down on the list.

Let me explain my use case better:

I have an app that has multiple businesses, and users within those businesses which have rights to perform certain functions for only documents that belong to that business. So the businessID (bid) is the group name when it comes to roles. So a user may have the 'manage-content' role for the 'koHXiA9E6SMMpe3PZ' group.

With this PR, the allow definition looks like this: 

```
allow: [{
    roles: 'manage-content',
    group ({bid}){ return bid;}
  }],
```

While I can accomplish this with the allow function, it involves much more boilerplate code, which this PR gets rid of:

```
allow: [{
    roles: true,
    group: true,
    allow({bid}){
      if(Roles.userIsInRole(this.userId,'manage-tv-content',bid) === false){
        return false;
      }else{
        //Test other fields if needed
        return true;
      }
    }
  }],
```

Also, I need to import the Roles package in the file, with this PR the additional import is not needed.

The idea of having an easy to look at method still applies, the group name is just a variable, not a static string.

**Comment by todda00** [comment]
any further thoughts on this PR? I need to decide on a direction for my use case, either creating a fork for this package, or include additional boilerplate code needed for each method when a variable group is needed. 

I think this is a valid use case and would love to see it implemented in the package, but if you really disagree, I understand.

**Comment by Didericis** [comment]
Makes sense; merged. Sorry for any inconvenience the 3 month hiatus might have caused. Are you still using this package/working in Meteor, and do you have any interest in taking this project over? I'm not doing much Meteor work anymore.

**Comment by todda00** [comment]
I am using Meteor and this package. Please add me as a contributor. I am not sure how to transfer a Meteor package from atmosphere though.
